### ISSUE TITLE
[Feature Request] Option to not mute pinned tabs

### ISSUE THREAD

**Issue by symbolisch1234** [evilpie/mute-all-inactive-tabs#2]
I sometimes have a youtube or soundcloud music mix playing in the background. I usually pin this tab, so if "Mute all inactive tabs" would give me the options to unmute this one, it'd be great. 

Alternatively please give me an option to keep specific tabs unmuted (though i believe this is harder to implement)... 

My current workaround is to move this tab into its own separate window, where it is always the active tab. This works, but it is very crude.

Cheers, and thanks for a great extension!

**Comment by evilpie** [comment]
If you manually unmute a tab, the extension should not mute that tab again, unless the music stops and starts to play again.

**Comment by symbolisch1234** [comment]
that is correct, but once i change the active tab (that is move to any other tab), the music stops again.

**Comment by evilpie** [comment]
Oh, yeah. I will implement it so that manually unmuted tabs are never muted again by the extension.

**Comment by evilpie** [comment]
Fixed in ac11184a156d57e8a2aa1a6b375d31fe491ee006. Version 0.2 is already on [AMO](https://addons.mozilla.org/en-US/firefox/addon/mute-all-inactive-tabs/).

**Comment by symbolisch1234** [comment]
perfect! it even restores the prior functionality if i manually mute it again. THANKS SO MUCH.
